services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - directus-cluster

  directus1:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://redis:6379"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
    depends_on:
      - redis
    networks:
      - directus-cluster

  directus2:
    image: directus/directus:latest
    ports:
      - "8056:8055"
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://redis:6379"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
    depends_on:
      - redis
    networks:
      - directus-cluster

  directus3:
    image: directus/directus:latest
    ports:
      - "8057:8055"
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://redis:6379"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
    depends_on:
      - redis
    networks:
      - directus-cluster

networks:
  directus-cluster:
    driver: bridge